require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PdfsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Pdf. As you add validations to Pdf, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PdfsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pdfs as @pdfs" do
      pdf = Pdf.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pdfs)).to eq([pdf])
    end
  end

  describe "GET show" do
    it "assigns the requested pdf as @pdf" do
      pdf = Pdf.create! valid_attributes
      get :show, {:id => pdf.to_param}, valid_session
      expect(assigns(:pdf)).to eq(pdf)
    end
  end

  describe "GET new" do
    it "assigns a new pdf as @pdf" do
      get :new, {}, valid_session
      expect(assigns(:pdf)).to be_a_new(Pdf)
    end
  end

  describe "GET edit" do
    it "assigns the requested pdf as @pdf" do
      pdf = Pdf.create! valid_attributes
      get :edit, {:id => pdf.to_param}, valid_session
      expect(assigns(:pdf)).to eq(pdf)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pdf" do
        expect {
          post :create, {:pdf => valid_attributes}, valid_session
        }.to change(Pdf, :count).by(1)
      end

      it "assigns a newly created pdf as @pdf" do
        post :create, {:pdf => valid_attributes}, valid_session
        expect(assigns(:pdf)).to be_a(Pdf)
        expect(assigns(:pdf)).to be_persisted
      end

      it "redirects to the created pdf" do
        post :create, {:pdf => valid_attributes}, valid_session
        expect(response).to redirect_to(Pdf.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pdf as @pdf" do
        post :create, {:pdf => invalid_attributes}, valid_session
        expect(assigns(:pdf)).to be_a_new(Pdf)
      end

      it "re-renders the 'new' template" do
        post :create, {:pdf => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pdf" do
        pdf = Pdf.create! valid_attributes
        put :update, {:id => pdf.to_param, :pdf => new_attributes}, valid_session
        pdf.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pdf as @pdf" do
        pdf = Pdf.create! valid_attributes
        put :update, {:id => pdf.to_param, :pdf => valid_attributes}, valid_session
        expect(assigns(:pdf)).to eq(pdf)
      end

      it "redirects to the pdf" do
        pdf = Pdf.create! valid_attributes
        put :update, {:id => pdf.to_param, :pdf => valid_attributes}, valid_session
        expect(response).to redirect_to(pdf)
      end
    end

    describe "with invalid params" do
      it "assigns the pdf as @pdf" do
        pdf = Pdf.create! valid_attributes
        put :update, {:id => pdf.to_param, :pdf => invalid_attributes}, valid_session
        expect(assigns(:pdf)).to eq(pdf)
      end

      it "re-renders the 'edit' template" do
        pdf = Pdf.create! valid_attributes
        put :update, {:id => pdf.to_param, :pdf => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pdf" do
      pdf = Pdf.create! valid_attributes
      expect {
        delete :destroy, {:id => pdf.to_param}, valid_session
      }.to change(Pdf, :count).by(-1)
    end

    it "redirects to the pdfs list" do
      pdf = Pdf.create! valid_attributes
      delete :destroy, {:id => pdf.to_param}, valid_session
      expect(response).to redirect_to(pdfs_url)
    end
  end

end
